// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/noho-digital/genny

package stringx

import (
	"errors"
	"fmt"
	"math/rand"
	"strings"
	"sync"
)

type StringSlice []string
type StringSliceReduceOption func(*StringSliceReduceOptions)
type StringSliceReduceOptions struct {
	initial string
}

type StringSliceAsyncOption func(options *StringSliceAsyncOptions)
type StringSliceAsyncOptions struct {
	PoolSize int
}

func NewStringSlice(items ...string) StringSlice {
	slice := make(StringSlice, len(items))
	for i, item := range items {
		slice[i] = item
	}
	return slice
}

func WithInitialString(t string) StringSliceReduceOption {
	return func(o *StringSliceReduceOptions) {
		o.initial = t
	}
}

func WhereStringAll(pl ...func(string) bool) func(string) bool {
	return func(t string) bool {
		for _, p := range pl {
			if !p(t) {
				return false
			}
		}
		return true
	}
}

func WhereStringAny(pl ...func(string) bool) func(string) bool {
	return func(t string) bool {
		for _, p := range pl {
			if p(t) {
				return true
			}
		}
		return false
	}
}

func WhereStringNot(p func(string) bool) func(string) bool {
	return func(t string) bool {
		return !p(t)
	}
}

func (slice StringSlice) Index(item string) int {
	for i, t := range slice {
		if item == t {
			return i
		}
	}
	return -1
}

// Returns copy of slice with only items that have non-default values
// (e.g. for pointer types all non-nil items)
func (slice StringSlice) Compact() StringSlice {
	var dfl string
	s := NewStringSlice()
	for _, t := range slice {
		if t == dfl {
			continue
		}
		s = append(s, t)
	}
	return s
}

func (slice StringSlice) Map(fn func(string) string) StringSlice {
	mapped := make(StringSlice, len(slice))
	for i, t := range slice {
		mapped[i] = fn(t)
	}
	return mapped
}

func (slice StringSlice) AsyncMap(fn func(string) string, options ...StringSliceAsyncOption) StringSlice {
	output := make(StringSlice, len(slice))
	eachFn := func(t string, i int) {
		v := fn(t)
		output[i] = v
	}
	slice.AsyncEachIndex(eachFn, options...)
	return output
}

func (slice StringSlice) MapString(fn func(string) string) []string {
	mapped := make([]string, len(slice))
	for i, t := range slice {
		mapped[i] = fn(t)
	}
	return mapped
}

func (slice StringSlice) AsyncMapString(fn func(string) string, options ...StringSliceAsyncOption) []string {
	output := make([]string, len(slice))
	eachFn := func(t string, i int) {
		v := fn(t)
		output[i] = v
	}
	slice.AsyncEachIndex(eachFn, options...)
	return output
}

func (slice StringSlice) MapBool(fn func(string) bool) []bool {
	mapped := make([]bool, len(slice))
	for i, t := range slice {
		mapped[i] = fn(t)
	}
	return mapped
}

func (slice StringSlice) AsyncMapBool(fn func(string) bool, options ...StringSliceAsyncOption) []bool {
	output := make([]bool, len(slice))
	eachFn := func(t string, i int) {
		v := fn(t)
		output[i] = v
	}
	slice.AsyncEachIndex(eachFn, options...)
	return output
}

func (slice StringSlice) Filter(where func(string) bool, ands ...func(string) bool) StringSlice {
	if len(ands) > 0 {
		where = WhereStringAll(append([]func(string) bool{where}, ands...)...)
	}
	var selected StringSlice
	for _, t := range slice {
		if where(t) {
			selected = append(selected, t)
		}
	}
	return selected
}

func (slice StringSlice) Reversed() StringSlice {
	s2 := make(StringSlice, len(slice))
	for i, j := 0, len(slice)-1; i < j; i, j = i+1, j-1 {
		s2[i] = slice[j]
	}
	r := slice.Copy()
	r.Reverse()
	return r
}

func (slice StringSlice) Reverse() {
	for i, j := 0, len(slice)-1; i < j; i, j = i+1, j-1 {
		slice[i], slice[j] = slice[j], slice[i]
	}
}

func (slice StringSlice) ReverseSelect(where func(string) bool, ands ...func(string) bool) StringSlice {
	if len(ands) > 0 {
		where = WhereStringAll(append([]func(string) bool{where}, ands...)...)
	}
	var selected StringSlice
	for i := len(slice) - 1; i >= 0; i-- {
		t := slice[i]
		if where(t) {
			selected = append(selected, t)
		}
	}
	return selected
}

func (slice StringSlice) IndexSelect(p func(string) bool) []int {
	var indexes []int
	for i, t := range slice {
		if p(t) {
			indexes = append(indexes, i)
		}
	}
	return indexes
}

// safe index access -- allows negative indexing, and will error instead of panic if out of bounds
func (slice StringSlice) Item(index int) (item string, err error) {
	if index < 0 {
		index = len(slice) - index
	}
	if index < 0 || index > len(slice)+1 {
		err = fmt.Errorf("index out of range")
	} else {
		item = slice[index]
	}
	return item, err
}

func (slice StringSlice) SelectAsync(p func(string) bool) StringSlice {
	var selected StringSlice
	hits := slice.AsyncMapBool(p)
	for i, t := range slice {
		if hits[i] {
			selected = append(selected, t)
		}
	}
	return selected
}

func (slice StringSlice) Reject(p func(string) bool) StringSlice {
	return slice.Filter(func(t string) bool { return !p(t) })
}

func (slice StringSlice) Reduce(operator func(string, string) string, options ...StringSliceReduceOption) (result string) {
	o := &StringSliceReduceOptions{}
	for _, opt := range options {
		opt(o)
	}
	result = o.initial
	for _, next := range slice {
		result = operator(result, next)
	}
	return result
}

// If no predicate function parameters given returns true if slice is not empty.
// Otherwise, will walk the slice backwards and return true for the first item where all the predicates
// return true
func (slice StringSlice) ReverseAny(criteria ...func(string) bool) bool {
	if len(criteria) == 0 {
		return len(slice) > 0
	}
	p := WhereStringAll(criteria...)
	for i := len(slice) - 1; i >= 0; i-- {
		t := slice[i]
		if p(t) {
			return true
		}
	}
	return false
}

// If no predicate function parameters given returns true if slice is not empty.
// Otherwise, will return true if all predicate function parameters return true for any item in the slice
func (slice StringSlice) Any(pl ...func(string) bool) bool {
	if len(pl) == 0 {
		return len(slice) > 0
	}
	p := WhereStringAll(pl...)
	for _, t := range slice {
		if p(t) {
			return true
		}
	}
	return false
}

func (slice StringSlice) ContainsAll(items ...string) bool {
	for _, item := range items {
		itemMatch := false
		for _, t := range slice {
			if item == t {
				itemMatch = true
				break
			}
		}
		if !itemMatch {
			return false
		}
	}
	return true
}

func (slice StringSlice) ContainsAny(items ...string) bool {
	for _, t := range slice {
		for _, item := range items {
			if item == t {
				return true
			}
		}
	}
	return false
}

func (slice StringSlice) PopLast() (last string, rest StringSlice) {
	l := len(slice)
	if l > 0 {
		last = slice[len(slice)-1]
	}
	if l > 1 {
		rest = slice[0 : len(slice)-1]
	}
	return last, rest
}

func (slice StringSlice) PopFirst() (first string, rest StringSlice) {
	l := len(slice)
	if l > 0 {
		first = slice[0]
	}
	if l > 1 {
		rest = slice[1:]
	}
	return first, rest
}

func (slice StringSlice) String() string {
	if slice == nil {
		return fmt.Sprint(nil)
	}
	return fmt.Sprintf("[%v]", strings.Join(slice.Strings(), ", "))
}

func (slice StringSlice) Strings() []string {
	return slice.MapString(func(x string) string {
		return fmt.Sprintf("%v", x)
	})
}
func (slice StringSlice) Pop(index int) (popped string, rest StringSlice) {
	if index < 0 {
		index = len(slice) - index
	}
	if index <= 0 {
		return slice.PopFirst()
	}
	if index >= len(slice)-1 {
		return slice.PopLast()
	}
	for i, item := range slice {
		if i == index {
			popped = item
		} else {
			rest = append(rest, item)
		}
	}
	return popped, rest
}

func (slice StringSlice) Contains(item string) bool {
	for _, t := range slice {
		if item == t {
			return true
		}
	}
	return false
}

func (slice StringSlice) AnyNot(pl ...func(string) bool) bool {
	return !slice.Any(pl...)
}

func (slice StringSlice) All(p func(string) bool) bool {
	for _, t := range slice {
		if !p(t) {
			return false
		}
	}
	return true
}

func (slice StringSlice) AllNot(p func(string) bool) bool {
	return !slice.All(p)
}

func (slice StringSlice) Append(items ...string) StringSlice {
	if slice == nil {
		var empty StringSlice
		return append(empty, items...)
	}
	return append(slice, items...)
}

func (slice StringSlice) Count(p func(string) bool) int {
	return len(slice.Filter(p))
}

func (slice StringSlice) Equal(other []string) bool {
	if len(slice) != len(other) {
		return false
	}
	for n := range slice {
		if slice[n] != other[n] {
			return false
		}
	}
	return true
}

func (slice StringSlice) Last(where ...func(string) bool) (last string) {
	hasCriteria := len(where) > 0
	matchesCriteria := WhereStringAll(where...)
	for i := len(slice) - 1; i >= 0; i-- {
		t := slice[i]
		if !hasCriteria || matchesCriteria(t) {
			last = t
			break
		}
	}
	return last
}

func (slice StringSlice) First(where ...func(string) bool) (first string) {
	hasCriteria := len(where) > 0
	matchesCriteria := WhereStringAll(where...)
	for _, t := range slice {
		if !hasCriteria || matchesCriteria(t) {
			first = t
			break
		}
	}
	return first
}

func (slice StringSlice) FirstIndex(where ...func(string) bool) int {
	if len(slice) == 0 {
		return -1
	}
	p := WhereStringAll(where...)
	for i, t := range slice {
		if p(t) {
			return i
		}
	}
	return -1
}

func (slice StringSlice) DistinctBy(match func(string, string) bool) (result StringSlice) {
Outer:
	for _, v := range slice {
		for _, r := range result {
			if match(v, r) {
				continue Outer
			}
		}
		result = append(result, v)
	}
	return result
}

func (slice StringSlice) Len() int {
	return len(slice)
}

func (slice StringSlice) Each(f func(string)) {
	for _, t := range slice {
		f(t)
	}
}

func (slice StringSlice) AsyncEach(f func(string), options ...StringSliceAsyncOption) {
	slice.AsyncEachIndex(func(t string, _ int) {
		f(t)
	}, options...)
}

func WithStringAsyncPoolSize(size int) StringSliceAsyncOption {
	return func(options *StringSliceAsyncOptions) {
		options.PoolSize = size
	}
}

func newStringSliceAsyncOptions(opts ...StringSliceAsyncOption) *StringSliceAsyncOptions {
	o := &StringSliceAsyncOptions{PoolSize: -1}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

func (slice StringSlice) AsyncEachIndex(f func(string, int), options ...StringSliceAsyncOption) {
	o := newStringSliceAsyncOptions(options...)
	if o.PoolSize <= 0 {
		wg := &sync.WaitGroup{}
		for index, item := range slice {
			wg.Add(1)
			go func(item string, index int) {
				f(item, index)
				wg.Done()
			}(item, index)
		}
		wg.Wait()
		return
	}
	pending := make(chan int, len(slice))
	completed := make(chan int, len(slice))
	for w := 0; w < o.PoolSize; w++ {
		go func(slice StringSlice, f func(string, int), pending <-chan int, completed chan<- int) {
			for index := range pending {
				item := slice[index]
				f(item, index)
				completed <- index
			}
		}(slice, f, pending, completed)
	}
	for index := range slice {
		pending <- index
	}
	close(pending)
	for range slice {
		<-completed
	}
}

func (slice StringSlice) EachIndex(f func(string, int)) {
	for i, t := range slice {
		f(t, i)
	}
}

func (slice StringSlice) Swap(i, j int) {
	slice[i], slice[j] = slice[j], slice[i]
}

func (slice StringSlice) Empty() bool {
	return len(slice) == 0
}

func (slice StringSlice) NotEmpty() bool {
	return len(slice) > 0
}

func (slice StringSlice) AsyncCopy() StringSlice {
	cp := make(StringSlice, len(slice))
	slice.AsyncEachIndex(func(_ string, i int) {
		cp[i] = slice[i]
	})
	return cp
}

func (slice StringSlice) Copy() StringSlice {
	cp := make(StringSlice, len(slice))
	for i := range slice {
		cp[i] = slice[i]
	}
	return cp
}

func (slice StringSlice) SortBy(less func(string, string) bool) {

	// Switch to heapsort if depth of 2*ceil(lg(n+1)) is reached.
	n := len(slice)
	maxDepth := 0
	for i := n; i > 0; i >>= 1 {
		maxDepth++
	}
	maxDepth *= 2
	__quickSortStringSlice(slice, less, 0, n, maxDepth)
}

func (slice StringSlice) SortedBy(less func(string, string) bool) StringSlice {
	cp := slice.Copy()
	cp.SortBy(less)
	return cp
}

func (slice StringSlice) IsSortedBy(less func(string, string) bool) bool {
	n := len(slice)
	for i := n - 1; i > 0; i-- {
		if less(slice[i], slice[i-1]) {
			return false
		}
	}
	return true
}

func (slice StringSlice) SortDescBy(less func(string, string) bool) {
	greater := func(a, b string) bool {
		return less(b, a)
	}
	slice.SortBy(greater)
}

func (slice StringSlice) SortedDescBy(less func(string, string) bool) StringSlice {
	greater := func(a, b string) bool {
		return less(b, a)
	}
	return slice.SortedBy(greater)
}

func (slice StringSlice) IsSortedDescBy(less func(string, string) bool) bool {
	greater := func(a, b string) bool {
		return less(b, a)
	}
	return slice.IsSortedBy(greater)
}

// Shuffled returns a copy of StringSlice with the contents shuffles using a version of the Fisher-Yates shuffle. See: http://clipperhouse.github.io/gen/#Shuffle
func (slice StringSlice) Shuffled() StringSlice {
	s := slice.Copy()
	s.Shuffle()
	return s
}

// Shuffle shuffles the contents of StringSlice in place using a version of the Fisher-Yates shuffle. See: http://clipperhouse.github.io/gen/#Shuffle
func (slice StringSlice) Shuffle() {
	total := len(slice)
	for i := 0; i < total; i++ {
		r := i + rand.Intn(total-i)
		slice[r], slice[i] = slice[i], slice[r]
	}
}

// MaxBy returns an element of StringSlice containing the maximum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MaxBy
func (slice StringSlice) MaxBy(less func(string, string) bool) (result string, err error) {
	l := len(slice)
	if l == 0 {
		err = errors.New("cannot determine the MaxBy of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if !less(slice[i], slice[m]) {
			m = i
		}
	}
	result = slice[m]
	return
}

// MinBy returns an element of StringSlice containing the minimum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MinBy
func (slice StringSlice) MinBy(less func(string, string) bool) (result string, err error) {
	l := len(slice)
	if l == 0 {
		err = errors.New("cannot determine the Min of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(slice[i], slice[m]) {
			m = i
		}
	}
	result = slice[m]
	return
}

func (slice StringSlice) AsyncReplaced(fn func(t string) string) StringSlice {
	s := slice.Copy()
	s.AsyncReplace(fn)
	return s
}

func (slice StringSlice) Replaced(fn func(t string) string) StringSlice {
	s := slice.Copy()
	s.Replace(fn)
	return s
}

func (slice StringSlice) Replace(fn func(t string) string) {
	for i, t := range slice {
		slice[i] = fn(t)
	}
}

func (slice StringSlice) AsyncReplace(fn func(t string) string, options ...StringSliceAsyncOption) {
	slice.AsyncEachIndex(func(t string, i int) {
		slice[i] = fn(t)
	}, options...)
}

func (slice StringSlice) SkipTake(skip, take int) StringSlice {
	var out StringSlice
	skipped := 0
	taken := 0
	for _, item := range slice {
		if skip > skipped {
			skipped++
			continue
		}
		out = append(out, item)
		taken++
		if take > 0 && taken >= take {
			break
		}
	}
	return out

}
func (slice StringSlice) Split(fn func(t string) bool) (StringSlice, StringSlice) {
	var a StringSlice
	var b StringSlice
	for _, t := range slice {
		if fn(t) {
			a = append(a, t)
		} else {
			b = append(b, t)
		}
	}
	return a, b
}

func __swapStringSlice(slice StringSlice, a, b int) {
	slice[a], slice[b] = slice[b], slice[a]
}

// Insertion sort
func __insertionSortStringSlice(slice StringSlice, less func(string, string) bool, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && less(slice[j], slice[j-1]); j-- {
			__swapStringSlice(slice, j, j-1)
		}
	}
}

// siftDown implements the heap property on slice[lo, hi).
// first is an offset into the array where the root of the heap lies.
func __siftDownStringSlice(slice StringSlice, less func(string, string) bool, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && less(slice[first+child], slice[first+child+1]) {
			child++
		}
		if !less(slice[first+root], slice[first+child]) {
			return
		}
		__swapStringSlice(slice, first+root, first+child)
		root = child
	}
}
func __heapSortStringSlice(slice StringSlice, less func(string, string) bool, a, b int) {
	first := a
	lo := 0
	hi := b - a
	// Build heap with greatest element at top.
	for i := (hi - 1) / 2; i >= 0; i-- {
		__siftDownStringSlice(slice, less, i, hi, first)
	}
	// Pop elements, largest first, into end of slice.
	for i := hi - 1; i >= 0; i-- {
		__swapStringSlice(slice, first, first+i)
		__siftDownStringSlice(slice, less, lo, i, first)
	}
}

// Quicksort, following Bentley and McIlroy,
// Engineering a Sort Function, SP&E November 1993.
// medianOfThree moves the median of the three values slice[a], slice[b], slice[c] into slice[a].
func __medianOfThreeStringSlice(slice StringSlice, less func(string, string) bool, a, b, c int) {
	m0 := b
	m1 := a
	m2 := c
	// bubble sort on 3 elements
	if less(slice[m1], slice[m0]) {
		__swapStringSlice(slice, m1, m0)
	}
	if less(slice[m2], slice[m1]) {
		__swapStringSlice(slice, m2, m1)
	}
	if less(slice[m1], slice[m0]) {
		__swapStringSlice(slice, m1, m0)
	}
	// now slice[m0] <= slice[m1] <= slice[m2]
}

func __swapRangeStringSlice(slice StringSlice, a, b, n int) {
	for i := 0; i < n; i++ {
		__swapStringSlice(slice, a+i, b+i)
	}
}
func __doPivotStringSlice(slice StringSlice, less func(string, string) bool, lo, hi int) (midlo, midhi int) {
	m := lo + (hi-lo)/2 // Written like this to avoid integer overflow.
	if hi-lo > 40 {
		// Tukey's Ninther, median of three medians of three.
		s := (hi - lo) / 8
		__medianOfThreeStringSlice(slice, less, lo, lo+s, lo+2*s)
		__medianOfThreeStringSlice(slice, less, m, m-s, m+s)
		__medianOfThreeStringSlice(slice, less, hi-1, hi-1-s, hi-1-2*s)
	}
	__medianOfThreeStringSlice(slice, less, lo, m, hi-1)
	// Invariants are:
	//	slice[lo] = pivot (set up by ChoosePivot)
	//	slice[lo <= i < a] = pivot
	//	slice[a <= i < b] < pivot
	//	slice[b <= i < c] is unexamined
	//	slice[c <= i < d] > pivot
	//	slice[d <= i < hi] = pivot
	//
	// Once b meets c, can swap the "= pivot" sections
	// into the middle of the slice.
	pivot := lo
	a, b, c, d := lo+1, lo+1, hi, hi
	for {
		for b < c {
			if less(slice[b], slice[pivot]) { // slice[b] < pivot
				b++
			} else if !less(slice[pivot], slice[b]) { // slice[b] = pivot
				__swapStringSlice(slice, a, b)
				a++
				b++
			} else {
				break
			}
		}
		for b < c {
			if less(slice[pivot], slice[c-1]) { // slice[c-1] > pivot
				c--
			} else if !less(slice[c-1], slice[pivot]) { // slice[c-1] = pivot
				__swapStringSlice(slice, c-1, d-1)
				c--
				d--
			} else {
				break
			}
		}
		if b >= c {
			break
		}
		// slice[b] > pivot; slice[c-1] < pivot
		__swapStringSlice(slice, b, c-1)
		b++
		c--
	}
	min := func(a, b int) int {
		if a < b {
			return a
		}
		return b
	}
	n := min(b-a, a-lo)
	__swapRangeStringSlice(slice, lo, b-n, n)
	n = min(hi-d, d-c)
	__swapRangeStringSlice(slice, c, hi-n, n)
	return lo + b - a, hi - (d - c)
}

func __quickSortStringSlice(slice StringSlice, less func(string, string) bool, a, b, maxDepth int) {
	for b-a > 7 {
		if maxDepth == 0 {
			__heapSortStringSlice(slice, less, a, b)
			return
		}
		maxDepth--
		mlo, mhi := __doPivotStringSlice(slice, less, a, b)
		// Avoiding recursion on the larger subproblem guarantees
		// a stack depth of at most lg(b-a).
		if mlo-a < b-mhi {
			__quickSortStringSlice(slice, less, a, mlo, maxDepth)
			a = mhi // i.e., quickSortStringSlice(slice, mhi, b)
		} else {
			__quickSortStringSlice(slice, less, mhi, b, maxDepth)
			b = mlo // i.e., quickSortStringSlice(slice, a, mlo)
		}
	}
	if b-a > 1 {
		__insertionSortStringSlice(slice, less, a, b)
	}
}
