// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/noho-digital/genny

package stringx

import (
	"errors"
	"fmt"
	"math/rand"
	"strings"
	"sync"
)

type StringSetSlice []StringSet
type StringSetSliceReduceOption func(*StringSetSliceReduceOptions)
type StringSetSliceReduceOptions struct {
	initial StringSet
}

type StringSetSliceAsyncOption func(options *StringSetSliceAsyncOptions)
type StringSetSliceAsyncOptions struct {
	PoolSize int
}

func NewStringSetSlice(items ...StringSet) StringSetSlice {
	slice := make(StringSetSlice, len(items))
	for i, item := range items {
		slice[i] = item
	}
	return slice
}

func WithInitialStringSet(t StringSet) StringSetSliceReduceOption {
	return func(o *StringSetSliceReduceOptions) {
		o.initial = t
	}
}

func WhereStringSetAll(pl ...func(StringSet) bool) func(StringSet) bool {
	return func(t StringSet) bool {
		for _, p := range pl {
			if !p(t) {
				return false
			}
		}
		return true
	}
}

func WhereStringSetAny(pl ...func(StringSet) bool) func(StringSet) bool {
	return func(t StringSet) bool {
		for _, p := range pl {
			if p(t) {
				return true
			}
		}
		return false
	}
}

func WhereStringSetNot(p func(StringSet) bool) func(StringSet) bool {
	return func(t StringSet) bool {
		return !p(t)
	}
}

func (slice StringSetSlice) Index(item StringSet) int {
	for i, t := range slice {
		if item == t {
			return i
		}
	}
	return -1
}

// Returns copy of slice with only items that have non-default values
// (e.g. for pointer types all non-nil items)
func (slice StringSetSlice) Compact() StringSetSlice {
	var dfl StringSet
	s := NewStringSetSlice()
	for _, t := range slice {
		if t == dfl {
			continue
		}
		s = append(s, t)
	}
	return s
}

func (slice StringSetSlice) Map(fn func(StringSet) StringSet) StringSetSlice {
	mapped := make(StringSetSlice, len(slice))
	for i, t := range slice {
		mapped[i] = fn(t)
	}
	return mapped
}

func (slice StringSetSlice) AsyncMap(fn func(StringSet) StringSet, options ...StringSetSliceAsyncOption) StringSetSlice {
	output := make(StringSetSlice, len(slice))
	eachFn := func(t StringSet, i int) {
		v := fn(t)
		output[i] = v
	}
	slice.AsyncEachIndex(eachFn, options...)
	return output
}

func (slice StringSetSlice) MapString(fn func(StringSet) string) []string {
	mapped := make([]string, len(slice))
	for i, t := range slice {
		mapped[i] = fn(t)
	}
	return mapped
}

func (slice StringSetSlice) AsyncMapString(fn func(StringSet) string, options ...StringSetSliceAsyncOption) []string {
	output := make([]string, len(slice))
	eachFn := func(t StringSet, i int) {
		v := fn(t)
		output[i] = v
	}
	slice.AsyncEachIndex(eachFn, options...)
	return output
}

func (slice StringSetSlice) MapBool(fn func(StringSet) bool) []bool {
	mapped := make([]bool, len(slice))
	for i, t := range slice {
		mapped[i] = fn(t)
	}
	return mapped
}

func (slice StringSetSlice) AsyncMapBool(fn func(StringSet) bool, options ...StringSetSliceAsyncOption) []bool {
	output := make([]bool, len(slice))
	eachFn := func(t StringSet, i int) {
		v := fn(t)
		output[i] = v
	}
	slice.AsyncEachIndex(eachFn, options...)
	return output
}

func (slice StringSetSlice) Filter(where func(StringSet) bool, ands ...func(StringSet) bool) StringSetSlice {
	if len(ands) > 0 {
		where = WhereStringSetAll(append([]func(StringSet) bool{where}, ands...)...)
	}
	var selected StringSetSlice
	for _, t := range slice {
		if where(t) {
			selected = append(selected, t)
		}
	}
	return selected
}

func (slice StringSetSlice) Reversed() StringSetSlice {
	s2 := make(StringSetSlice, len(slice))
	for i, j := 0, len(slice)-1; i < j; i, j = i+1, j-1 {
		s2[i] = slice[j]
	}
	r := slice.Copy()
	r.Reverse()
	return r
}

func (slice StringSetSlice) Reverse() {
	for i, j := 0, len(slice)-1; i < j; i, j = i+1, j-1 {
		slice[i], slice[j] = slice[j], slice[i]
	}
}

func (slice StringSetSlice) ReverseSelect(where func(StringSet) bool, ands ...func(StringSet) bool) StringSetSlice {
	if len(ands) > 0 {
		where = WhereStringSetAll(append([]func(StringSet) bool{where}, ands...)...)
	}
	var selected StringSetSlice
	for i := len(slice) - 1; i >= 0; i-- {
		t := slice[i]
		if where(t) {
			selected = append(selected, t)
		}
	}
	return selected
}

func (slice StringSetSlice) IndexSelect(p func(StringSet) bool) []int {
	var indexes []int
	for i, t := range slice {
		if p(t) {
			indexes = append(indexes, i)
		}
	}
	return indexes
}

// safe index access -- allows negative indexing, and will error instead of panic if out of bounds
func (slice StringSetSlice) Item(index int) (item StringSet, err error) {
	if index < 0 {
		index = len(slice) - index
	}
	if index < 0 || index > len(slice)+1 {
		err = fmt.Errorf("index out of range")
	} else {
		item = slice[index]
	}
	return item, err
}

func (slice StringSetSlice) SelectAsync(p func(StringSet) bool) StringSetSlice {
	var selected StringSetSlice
	hits := slice.AsyncMapBool(p)
	for i, t := range slice {
		if hits[i] {
			selected = append(selected, t)
		}
	}
	return selected
}

func (slice StringSetSlice) Reject(p func(StringSet) bool) StringSetSlice {
	return slice.Filter(func(t StringSet) bool { return !p(t) })
}

func (slice StringSetSlice) Reduce(operator func(StringSet, StringSet) StringSet, options ...StringSetSliceReduceOption) (result StringSet) {
	o := &StringSetSliceReduceOptions{}
	for _, opt := range options {
		opt(o)
	}
	result = o.initial
	for _, next := range slice {
		result = operator(result, next)
	}
	return result
}

// If no predicate function parameters given returns true if slice is not empty.
// Otherwise, will walk the slice backwards and return true for the first item where all the predicates
// return true
func (slice StringSetSlice) ReverseAny(criteria ...func(StringSet) bool) bool {
	if len(criteria) == 0 {
		return len(slice) > 0
	}
	p := WhereStringSetAll(criteria...)
	for i := len(slice) - 1; i >= 0; i-- {
		t := slice[i]
		if p(t) {
			return true
		}
	}
	return false
}

// If no predicate function parameters given returns true if slice is not empty.
// Otherwise, will return true if all predicate function parameters return true for any item in the slice
func (slice StringSetSlice) Any(pl ...func(StringSet) bool) bool {
	if len(pl) == 0 {
		return len(slice) > 0
	}
	p := WhereStringSetAll(pl...)
	for _, t := range slice {
		if p(t) {
			return true
		}
	}
	return false
}

func (slice StringSetSlice) ContainsAll(items ...StringSet) bool {
	for _, item := range items {
		itemMatch := false
		for _, t := range slice {
			if item == t {
				itemMatch = true
				break
			}
		}
		if !itemMatch {
			return false
		}
	}
	return true
}

func (slice StringSetSlice) ContainsAny(items ...StringSet) bool {
	for _, t := range slice {
		for _, item := range items {
			if item == t {
				return true
			}
		}
	}
	return false
}

func (slice StringSetSlice) PopLast() (last StringSet, rest StringSetSlice) {
	l := len(slice)
	if l > 0 {
		last = slice[len(slice)-1]
	}
	if l > 1 {
		rest = slice[0 : len(slice)-1]
	}
	return last, rest
}

func (slice StringSetSlice) PopFirst() (first StringSet, rest StringSetSlice) {
	l := len(slice)
	if l > 0 {
		first = slice[0]
	}
	if l > 1 {
		rest = slice[1:]
	}
	return first, rest
}

func (slice StringSetSlice) String() string {
	if slice == nil {
		return fmt.Sprint(nil)
	}
	return fmt.Sprintf("[%v]", strings.Join(slice.Strings(), ", "))
}

func (slice StringSetSlice) Strings() []string {
	return slice.MapString(func(x StringSet) string {
		return fmt.Sprintf("%v", x)
	})
}
func (slice StringSetSlice) Pop(index int) (popped StringSet, rest StringSetSlice) {
	if index < 0 {
		index = len(slice) - index
	}
	if index <= 0 {
		return slice.PopFirst()
	}
	if index >= len(slice)-1 {
		return slice.PopLast()
	}
	for i, item := range slice {
		if i == index {
			popped = item
		} else {
			rest = append(rest, item)
		}
	}
	return popped, rest
}

func (slice StringSetSlice) Contains(item StringSet) bool {
	for _, t := range slice {
		if item == t {
			return true
		}
	}
	return false
}

func (slice StringSetSlice) AnyNot(pl ...func(StringSet) bool) bool {
	return !slice.Any(pl...)
}

func (slice StringSetSlice) All(p func(StringSet) bool) bool {
	for _, t := range slice {
		if !p(t) {
			return false
		}
	}
	return true
}

func (slice StringSetSlice) AllNot(p func(StringSet) bool) bool {
	return !slice.All(p)
}

func (slice StringSetSlice) Append(items ...StringSet) StringSetSlice {
	if slice == nil {
		var empty StringSetSlice
		return append(empty, items...)
	}
	return append(slice, items...)
}

func (slice StringSetSlice) Count(p func(StringSet) bool) int {
	return len(slice.Filter(p))
}

func (slice StringSetSlice) Equal(other []StringSet) bool {
	if len(slice) != len(other) {
		return false
	}
	for n := range slice {
		if slice[n] != other[n] {
			return false
		}
	}
	return true
}

func (slice StringSetSlice) Last(where ...func(StringSet) bool) (last StringSet) {
	hasCriteria := len(where) > 0
	matchesCriteria := WhereStringSetAll(where...)
	for i := len(slice) - 1; i >= 0; i-- {
		t := slice[i]
		if !hasCriteria || matchesCriteria(t) {
			last = t
			break
		}
	}
	return last
}

func (slice StringSetSlice) First(where ...func(StringSet) bool) (first StringSet) {
	hasCriteria := len(where) > 0
	matchesCriteria := WhereStringSetAll(where...)
	for _, t := range slice {
		if !hasCriteria || matchesCriteria(t) {
			first = t
			break
		}
	}
	return first
}

func (slice StringSetSlice) FirstIndex(where ...func(StringSet) bool) int {
	if len(slice) == 0 {
		return -1
	}
	p := WhereStringSetAll(where...)
	for i, t := range slice {
		if p(t) {
			return i
		}
	}
	return -1
}

func (slice StringSetSlice) DistinctBy(match func(StringSet, StringSet) bool) (result StringSetSlice) {
Outer:
	for _, v := range slice {
		for _, r := range result {
			if match(v, r) {
				continue Outer
			}
		}
		result = append(result, v)
	}
	return result
}

func (slice StringSetSlice) Len() int {
	return len(slice)
}

func (slice StringSetSlice) Each(f func(StringSet)) {
	for _, t := range slice {
		f(t)
	}
}

func (slice StringSetSlice) AsyncEach(f func(StringSet), options ...StringSetSliceAsyncOption) {
	slice.AsyncEachIndex(func(t StringSet, _ int) {
		f(t)
	}, options...)
}

func WithStringSetAsyncPoolSize(size int) StringSetSliceAsyncOption {
	return func(options *StringSetSliceAsyncOptions) {
		options.PoolSize = size
	}
}

func newStringSetSliceAsyncOptions(opts ...StringSetSliceAsyncOption) *StringSetSliceAsyncOptions {
	o := &StringSetSliceAsyncOptions{PoolSize: -1}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

func (slice StringSetSlice) AsyncEachIndex(f func(StringSet, int), options ...StringSetSliceAsyncOption) {
	o := newStringSetSliceAsyncOptions(options...)
	if o.PoolSize <= 0 {
		wg := &sync.WaitGroup{}
		for index, item := range slice {
			wg.Add(1)
			go func(item StringSet, index int) {
				f(item, index)
				wg.Done()
			}(item, index)
		}
		wg.Wait()
		return
	}
	pending := make(chan int, len(slice))
	completed := make(chan int, len(slice))
	for w := 0; w < o.PoolSize; w++ {
		go func(slice StringSetSlice, f func(StringSet, int), pending <-chan int, completed chan<- int) {
			for index := range pending {
				item := slice[index]
				f(item, index)
				completed <- index
			}
		}(slice, f, pending, completed)
	}
	for index := range slice {
		pending <- index
	}
	close(pending)
	for range slice {
		<-completed
	}
}

func (slice StringSetSlice) EachIndex(f func(StringSet, int)) {
	for i, t := range slice {
		f(t, i)
	}
}

func (slice StringSetSlice) Swap(i, j int) {
	slice[i], slice[j] = slice[j], slice[i]
}

func (slice StringSetSlice) Empty() bool {
	return len(slice) == 0
}

func (slice StringSetSlice) NotEmpty() bool {
	return len(slice) > 0
}

func (slice StringSetSlice) AsyncCopy() StringSetSlice {
	cp := make(StringSetSlice, len(slice))
	slice.AsyncEachIndex(func(_ StringSet, i int) {
		cp[i] = slice[i]
	})
	return cp
}

func (slice StringSetSlice) Copy() StringSetSlice {
	cp := make(StringSetSlice, len(slice))
	for i := range slice {
		cp[i] = slice[i]
	}
	return cp
}

func (slice StringSetSlice) SortBy(less func(StringSet, StringSet) bool) {

	// Switch to heapsort if depth of 2*ceil(lg(n+1)) is reached.
	n := len(slice)
	maxDepth := 0
	for i := n; i > 0; i >>= 1 {
		maxDepth++
	}
	maxDepth *= 2
	__quickSortStringSetSlice(slice, less, 0, n, maxDepth)
}

func (slice StringSetSlice) SortedBy(less func(StringSet, StringSet) bool) StringSetSlice {
	cp := slice.Copy()
	cp.SortBy(less)
	return cp
}

func (slice StringSetSlice) IsSortedBy(less func(StringSet, StringSet) bool) bool {
	n := len(slice)
	for i := n - 1; i > 0; i-- {
		if less(slice[i], slice[i-1]) {
			return false
		}
	}
	return true
}

func (slice StringSetSlice) SortDescBy(less func(StringSet, StringSet) bool) {
	greater := func(a, b StringSet) bool {
		return less(b, a)
	}
	slice.SortBy(greater)
}

func (slice StringSetSlice) SortedDescBy(less func(StringSet, StringSet) bool) StringSetSlice {
	greater := func(a, b StringSet) bool {
		return less(b, a)
	}
	return slice.SortedBy(greater)
}

func (slice StringSetSlice) IsSortedDescBy(less func(StringSet, StringSet) bool) bool {
	greater := func(a, b StringSet) bool {
		return less(b, a)
	}
	return slice.IsSortedBy(greater)
}

// Shuffled returns a copy of StringSetSlice with the contents shuffles using a version of the Fisher-Yates shuffle. See: http://clipperhouse.github.io/gen/#Shuffle
func (slice StringSetSlice) Shuffled() StringSetSlice {
	s := slice.Copy()
	s.Shuffle()
	return s
}

// Shuffle shuffles the contents of StringSetSlice in place using a version of the Fisher-Yates shuffle. See: http://clipperhouse.github.io/gen/#Shuffle
func (slice StringSetSlice) Shuffle() {
	total := len(slice)
	for i := 0; i < total; i++ {
		r := i + rand.Intn(total-i)
		slice[r], slice[i] = slice[i], slice[r]
	}
}

// MaxBy returns an element of StringSetSlice containing the maximum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MaxBy
func (slice StringSetSlice) MaxBy(less func(StringSet, StringSet) bool) (result StringSet, err error) {
	l := len(slice)
	if l == 0 {
		err = errors.New("cannot determine the MaxBy of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if !less(slice[i], slice[m]) {
			m = i
		}
	}
	result = slice[m]
	return
}

// MinBy returns an element of StringSetSlice containing the minimum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MinBy
func (slice StringSetSlice) MinBy(less func(StringSet, StringSet) bool) (result StringSet, err error) {
	l := len(slice)
	if l == 0 {
		err = errors.New("cannot determine the Min of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(slice[i], slice[m]) {
			m = i
		}
	}
	result = slice[m]
	return
}

func (slice StringSetSlice) AsyncReplaced(fn func(t StringSet) StringSet) StringSetSlice {
	s := slice.Copy()
	s.AsyncReplace(fn)
	return s
}

func (slice StringSetSlice) Replaced(fn func(t StringSet) StringSet) StringSetSlice {
	s := slice.Copy()
	s.Replace(fn)
	return s
}

func (slice StringSetSlice) Replace(fn func(t StringSet) StringSet) {
	for i, t := range slice {
		slice[i] = fn(t)
	}
}

func (slice StringSetSlice) AsyncReplace(fn func(t StringSet) StringSet, options ...StringSetSliceAsyncOption) {
	slice.AsyncEachIndex(func(t StringSet, i int) {
		slice[i] = fn(t)
	}, options...)
}

func (slice StringSetSlice) SkipTake(skip, take int) StringSetSlice {
	var out StringSetSlice
	skipped := 0
	taken := 0
	for _, item := range slice {
		if skip > skipped {
			skipped++
			continue
		}
		out = append(out, item)
		taken++
		if take > 0 && taken >= take {
			break
		}
	}
	return out

}
func (slice StringSetSlice) Split(fn func(t StringSet) bool) (StringSetSlice, StringSetSlice) {
	var a StringSetSlice
	var b StringSetSlice
	for _, t := range slice {
		if fn(t) {
			a = append(a, t)
		} else {
			b = append(b, t)
		}
	}
	return a, b
}

func __swapStringSetSlice(slice StringSetSlice, a, b int) {
	slice[a], slice[b] = slice[b], slice[a]
}

// Insertion sort
func __insertionSortStringSetSlice(slice StringSetSlice, less func(StringSet, StringSet) bool, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && less(slice[j], slice[j-1]); j-- {
			__swapStringSetSlice(slice, j, j-1)
		}
	}
}

// siftDown implements the heap property on slice[lo, hi).
// first is an offset into the array where the root of the heap lies.
func __siftDownStringSetSlice(slice StringSetSlice, less func(StringSet, StringSet) bool, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && less(slice[first+child], slice[first+child+1]) {
			child++
		}
		if !less(slice[first+root], slice[first+child]) {
			return
		}
		__swapStringSetSlice(slice, first+root, first+child)
		root = child
	}
}
func __heapSortStringSetSlice(slice StringSetSlice, less func(StringSet, StringSet) bool, a, b int) {
	first := a
	lo := 0
	hi := b - a
	// Build heap with greatest element at top.
	for i := (hi - 1) / 2; i >= 0; i-- {
		__siftDownStringSetSlice(slice, less, i, hi, first)
	}
	// Pop elements, largest first, into end of slice.
	for i := hi - 1; i >= 0; i-- {
		__swapStringSetSlice(slice, first, first+i)
		__siftDownStringSetSlice(slice, less, lo, i, first)
	}
}

// Quicksort, following Bentley and McIlroy,
// Engineering a Sort Function, SP&E November 1993.
// medianOfThree moves the median of the three values slice[a], slice[b], slice[c] into slice[a].
func __medianOfThreeStringSetSlice(slice StringSetSlice, less func(StringSet, StringSet) bool, a, b, c int) {
	m0 := b
	m1 := a
	m2 := c
	// bubble sort on 3 elements
	if less(slice[m1], slice[m0]) {
		__swapStringSetSlice(slice, m1, m0)
	}
	if less(slice[m2], slice[m1]) {
		__swapStringSetSlice(slice, m2, m1)
	}
	if less(slice[m1], slice[m0]) {
		__swapStringSetSlice(slice, m1, m0)
	}
	// now slice[m0] <= slice[m1] <= slice[m2]
}

func __swapRangeStringSetSlice(slice StringSetSlice, a, b, n int) {
	for i := 0; i < n; i++ {
		__swapStringSetSlice(slice, a+i, b+i)
	}
}
func __doPivotStringSetSlice(slice StringSetSlice, less func(StringSet, StringSet) bool, lo, hi int) (midlo, midhi int) {
	m := lo + (hi-lo)/2 // Written like this to avoid integer overflow.
	if hi-lo > 40 {
		// Tukey's Ninther, median of three medians of three.
		s := (hi - lo) / 8
		__medianOfThreeStringSetSlice(slice, less, lo, lo+s, lo+2*s)
		__medianOfThreeStringSetSlice(slice, less, m, m-s, m+s)
		__medianOfThreeStringSetSlice(slice, less, hi-1, hi-1-s, hi-1-2*s)
	}
	__medianOfThreeStringSetSlice(slice, less, lo, m, hi-1)
	// Invariants are:
	//	slice[lo] = pivot (set up by ChoosePivot)
	//	slice[lo <= i < a] = pivot
	//	slice[a <= i < b] < pivot
	//	slice[b <= i < c] is unexamined
	//	slice[c <= i < d] > pivot
	//	slice[d <= i < hi] = pivot
	//
	// Once b meets c, can swap the "= pivot" sections
	// into the middle of the slice.
	pivot := lo
	a, b, c, d := lo+1, lo+1, hi, hi
	for {
		for b < c {
			if less(slice[b], slice[pivot]) { // slice[b] < pivot
				b++
			} else if !less(slice[pivot], slice[b]) { // slice[b] = pivot
				__swapStringSetSlice(slice, a, b)
				a++
				b++
			} else {
				break
			}
		}
		for b < c {
			if less(slice[pivot], slice[c-1]) { // slice[c-1] > pivot
				c--
			} else if !less(slice[c-1], slice[pivot]) { // slice[c-1] = pivot
				__swapStringSetSlice(slice, c-1, d-1)
				c--
				d--
			} else {
				break
			}
		}
		if b >= c {
			break
		}
		// slice[b] > pivot; slice[c-1] < pivot
		__swapStringSetSlice(slice, b, c-1)
		b++
		c--
	}
	min := func(a, b int) int {
		if a < b {
			return a
		}
		return b
	}
	n := min(b-a, a-lo)
	__swapRangeStringSetSlice(slice, lo, b-n, n)
	n = min(hi-d, d-c)
	__swapRangeStringSetSlice(slice, c, hi-n, n)
	return lo + b - a, hi - (d - c)
}

func __quickSortStringSetSlice(slice StringSetSlice, less func(StringSet, StringSet) bool, a, b, maxDepth int) {
	for b-a > 7 {
		if maxDepth == 0 {
			__heapSortStringSetSlice(slice, less, a, b)
			return
		}
		maxDepth--
		mlo, mhi := __doPivotStringSetSlice(slice, less, a, b)
		// Avoiding recursion on the larger subproblem guarantees
		// a stack depth of at most lg(b-a).
		if mlo-a < b-mhi {
			__quickSortStringSetSlice(slice, less, a, mlo, maxDepth)
			a = mhi // i.e., quickSortStringSetSlice(slice, mhi, b)
		} else {
			__quickSortStringSetSlice(slice, less, mhi, b, maxDepth)
			b = mlo // i.e., quickSortStringSetSlice(slice, a, mlo)
		}
	}
	if b-a > 1 {
		__insertionSortStringSetSlice(slice, less, a, b)
	}
}
