// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/noho-digital/genny

package stringx

func (slice StringSlice) Distinct() StringSlice {
	var uniques StringSlice
	seen := make(map[string]bool)
	for _, t := range slice {
		_, ok := seen[t]
		if ok {
			continue
		}
		seen[t] = true
		uniques = append(uniques, t)
	}
	return uniques
}
