// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/noho-digital/genny

package stringx

import (
	"errors"
	"math/rand"
	"runtime"
)

type StringSliceSlice []StringSlice
type StringSliceSliceReduceOption func(*StringSliceSliceReduceOptions)
type StringSliceSliceReduceOptions struct {
	initial StringSlice
}

type StringSliceSliceAsyncOption func(options *StringSliceSliceAsyncOptions)
type StringSliceSliceAsyncOptions struct {
	PoolSize int
}

func WithStringSliceAsyncPoolSize(size int) StringSliceSliceAsyncOption {
	return func(options *StringSliceSliceAsyncOptions) {
		options.PoolSize = size
	}
}

func NewStringSliceSlice(items ...StringSlice) StringSliceSlice {
	slice := make(StringSliceSlice, len(items))
	for i, item := range items {
		slice[i] = item
	}
	return slice
}

func WithInitialStringSlice(t StringSlice) StringSliceSliceReduceOption {
	return func(o *StringSliceSliceReduceOptions) {
		o.initial = t
	}
}

func WhereStringSliceAll(pl ...func(StringSlice) bool) func(StringSlice) bool {
	return func(t StringSlice) bool {
		for _, p := range pl {
			if !p(t) {
				return false
			}
		}
		return true
	}
}

func WhereStringSliceAny(pl ...func(StringSlice) bool) func(StringSlice) bool {
	return func(t StringSlice) bool {
		for _, p := range pl {
			if p(t) {
				return true
			}
		}
		return false
	}
}

func WhereStringSliceNot(p func(StringSlice) bool) func(StringSlice) bool {
	return func(t StringSlice) bool {
		return !p(t)
	}
}

func (slice StringSliceSlice) Map(fn func(StringSlice) StringSlice) StringSliceSlice {
	mapped := make(StringSliceSlice, len(slice))
	for i, t := range slice {
		mapped[i] = fn(t)
	}
	return mapped
}

func (slice StringSliceSlice) AsyncMap(fn func(StringSlice) StringSlice, options ...StringSliceSliceAsyncOption) StringSliceSlice {
	output := make(StringSliceSlice, len(slice))
	eachFn := func(t StringSlice, i int) {
		v := fn(t)
		output[i] = v
	}
	slice.AsyncEachIndex(eachFn, options...)
	return output
}

func (slice StringSliceSlice) MapString(fn func(StringSlice) string) []string {
	mapped := make([]string, len(slice))
	for i, t := range slice {
		mapped[i] = fn(t)
	}
	return mapped
}

func (slice StringSliceSlice) AsyncMapString(fn func(StringSlice) string, options ...StringSliceSliceAsyncOption) []string {
	output := make([]string, len(slice))
	eachFn := func(t StringSlice, i int) {
		v := fn(t)
		output[i] = v
	}
	slice.AsyncEachIndex(eachFn, options...)
	return output
}

func (slice StringSliceSlice) MapBool(fn func(StringSlice) bool) []bool {
	mapped := make([]bool, len(slice))
	for i, t := range slice {
		mapped[i] = fn(t)
	}
	return mapped
}

func (slice StringSliceSlice) AsyncMapBool(fn func(StringSlice) bool, options ...StringSliceSliceAsyncOption) []bool {
	output := make([]bool, len(slice))
	eachFn := func(t StringSlice, i int) {
		v := fn(t)
		output[i] = v
	}
	slice.AsyncEachIndex(eachFn, options...)
	return output
}

func (slice StringSliceSlice) Filter(p func(StringSlice) bool) StringSliceSlice {
	var selected StringSliceSlice
	for _, t := range slice {
		if p(t) {
			selected = append(selected, t)
		}
	}
	return selected
}

func (slice StringSliceSlice) IndexSelect(p func(StringSlice) bool) []int {
	var indexes []int
	for i, t := range slice {
		if p(t) {
			indexes = append(indexes, i)
		}
	}
	return indexes
}

func (slice StringSliceSlice) SelectAsync(p func(StringSlice) bool) StringSliceSlice {
	var selected StringSliceSlice
	hits := slice.AsyncMapBool(p)
	for i, t := range slice {
		if hits[i] {
			selected = append(selected, t)
		}
	}
	return selected
}

func (slice StringSliceSlice) Reject(p func(StringSlice) bool) StringSliceSlice {
	return slice.Filter(func(t StringSlice) bool { return !p(t) })
}

func (slice StringSliceSlice) Reduce(operator func(StringSlice, StringSlice) StringSlice, options ...StringSliceSliceReduceOption) (result StringSlice) {
	o := &StringSliceSliceReduceOptions{}
	for _, opt := range options {
		opt(o)
	}
	result = o.initial
	for _, next := range slice {
		result = operator(result, next)
	}
	return result
}

// If no predicate function parameters given returns true if slice is not empty.
// Otherwise, will return true if all predicate function parameters return true for any item in the slice
func (slice StringSliceSlice) Any(pl ...func(StringSlice) bool) bool {
	if len(pl) == 0 {
		return len(slice) > 0
	}
	p := WhereStringSliceAll(pl...)
	for _, t := range slice {
		if p(t) {
			return true
		}
	}
	return false
}

func (slice StringSliceSlice) AnyNot(pl ...func(StringSlice) bool) bool {
	return !slice.Any(pl...)
}

func (slice StringSliceSlice) All(p func(StringSlice) bool) bool {
	for _, t := range slice {
		if !p(t) {
			return false
		}
	}
	return true
}

func (slice StringSliceSlice) AllNot(p func(StringSlice) bool) bool {
	return !slice.All(p)
}

func (slice StringSliceSlice) Append(items ...StringSlice) StringSliceSlice {
	if slice == nil {
		var empty StringSliceSlice
		return append(empty, items...)
	}
	return append(slice, items...)
}

func (slice StringSliceSlice) Count(p func(StringSlice) bool) int {
	return len(slice.Filter(p))
}

func (slice StringSliceSlice) First(where ...func(StringSlice) bool) StringSlice {
	var r StringSlice
	if len(slice) == 0 {
		return r
	}
	p := WhereStringSliceAll(where...)
	for _, t := range slice {
		if p(t) {
			r = t
			break
		}
	}
	return r
}

func (slice StringSliceSlice) FirstIndex(where ...func(StringSlice) bool) int {
	if len(slice) == 0 {
		return -1
	}
	p := WhereStringSliceAll(where...)
	for i, t := range slice {
		if p(t) {
			return i
		}
	}
	return -1
}

func (slice StringSliceSlice) DistinctBy(match func(StringSlice, StringSlice) bool) (result StringSliceSlice) {
Outer:
	for _, v := range slice {
		for _, r := range result {
			if match(v, r) {
				continue Outer
			}
		}
		result = append(result, v)
	}
	return result
}

func (slice StringSliceSlice) Len() int {
	return len(slice)
}

func (slice StringSliceSlice) Each(f func(StringSlice)) {
	for _, t := range slice {
		f(t)
	}
}

func (slice StringSliceSlice) AsyncEach(f func(StringSlice)) {
	slice.AsyncEachIndex(func(t StringSlice, _ int) {
		f(t)
	})
}

func newStringSliceSliceAsyncOptions(opts ...StringSliceSliceAsyncOption) *StringSliceSliceAsyncOptions {
	o := &StringSliceSliceAsyncOptions{PoolSize: runtime.NumCPU()}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

func __StringSliceSliceEachIndexAsyncWorker(slice StringSliceSlice, f func(StringSlice, int), pending <-chan int, completed chan<- int) {
	for index := range pending {
		item := slice[index]
		f(item, index)
		completed <- index
	}
}

func (slice StringSliceSlice) AsyncEachIndex(f func(StringSlice, int), options ...StringSliceSliceAsyncOption) {
	o := newStringSliceSliceAsyncOptions(options...)
	pending := make(chan int, len(slice))
	completed := make(chan int, len(slice))
	for w := 0; w < o.PoolSize; w++ {
		go __StringSliceSliceEachIndexAsyncWorker(slice, f, pending, completed)
	}
	for index := range slice {
		pending <- index
	}
	close(pending)
	for _ = range slice {
		<-completed
	}
}

func (slice StringSliceSlice) EachIndex(f func(StringSlice, int)) {
	for i, t := range slice {
		f(t, i)
	}
}

func (slice StringSliceSlice) Swap(i, j int) {
	slice[i], slice[j] = slice[j], slice[i]
}

func (slice StringSliceSlice) Empty() bool {
	return len(slice) == 0
}

func (slice StringSliceSlice) NotEmpty() bool {
	return len(slice) > 0
}

func (slice StringSliceSlice) Copy() StringSliceSlice {
	cp := make(StringSliceSlice, len(slice))
	for i := range slice {
		cp[i] = slice[i]
	}
	return cp
}

func (slice StringSliceSlice) Replace(fn func(t StringSlice) StringSlice) {
	for i, t := range slice {
		slice[i] = fn(t)
	}
}

func (slice StringSliceSlice) AsyncReplace(fn func(t StringSlice) StringSlice, options ...StringSliceSliceAsyncOption) {
	slice.AsyncEachIndex(func(t StringSlice, i int) {
		slice[i] = fn(t)
	}, options...)
}

func (slice StringSliceSlice) Reversed() StringSliceSlice {
	r := slice.Copy()
	r.Reverse()
	return r
}

func (slice StringSliceSlice) Reverse() {
	for i, j := 0, len(slice)-1; i < j; i, j = i+1, j-1 {
		slice[i], slice[j] = slice[j], slice[i]
	}
}

func (slice StringSliceSlice) SortBy(less func(StringSlice, StringSlice) bool) {

	// Switch to heapsort if depth of 2*ceil(lg(n+1)) is reached.
	n := len(slice)
	maxDepth := 0
	for i := n; i > 0; i >>= 1 {
		maxDepth++
	}
	maxDepth *= 2
	quickSortStringSliceSlice(slice, less, 0, n, maxDepth)
}

func (slice StringSliceSlice) SortedBy(less func(StringSlice, StringSlice) bool) StringSliceSlice {
	cp := slice.Copy()
	cp.SortBy(less)
	return cp
}

func (slice StringSliceSlice) IsSortedBy(less func(StringSlice, StringSlice) bool) bool {
	n := len(slice)
	for i := n - 1; i > 0; i-- {
		if less(slice[i], slice[i-1]) {
			return false
		}
	}
	return true
}

func (slice StringSliceSlice) SortDescBy(less func(StringSlice, StringSlice) bool) {
	greater := func(a, b StringSlice) bool {
		return less(b, a)
	}
	slice.SortBy(greater)
}

func (slice StringSliceSlice) SortedDescBy(less func(StringSlice, StringSlice) bool) StringSliceSlice {
	greater := func(a, b StringSlice) bool {
		return less(b, a)
	}
	return slice.SortedBy(greater)
}

func (slice StringSliceSlice) IsSortedDescBy(less func(StringSlice, StringSlice) bool) bool {
	greater := func(a, b StringSlice) bool {
		return less(b, a)
	}
	return slice.IsSortedBy(greater)
}

// Shuffled returns a copy of StringSliceSlice with the contents shuffles using a version of the Fisher-Yates shuffle. See: http://clipperhouse.github.io/gen/#Shuffle
func (slice StringSliceSlice) Shuffled() StringSliceSlice {
	s := slice.Copy()
	s.Shuffle()
	return s
}

// Shuffle shuffles the contents of StringSliceSlice in place using a version of the Fisher-Yates shuffle. See: http://clipperhouse.github.io/gen/#Shuffle
func (slice StringSliceSlice) Shuffle() {
	total := len(slice)
	for i := 0; i < total; i++ {
		r := i + rand.Intn(total-i)
		slice[r], slice[i] = slice[i], slice[r]
	}
}

// MaxBy returns an element of StringSliceSlice containing the maximum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MaxBy
func (slice StringSliceSlice) MaxBy(less func(StringSlice, StringSlice) bool) (result StringSlice, err error) {
	l := len(slice)
	if l == 0 {
		err = errors.New("cannot determine the MaxBy of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if !less(slice[i], slice[m]) {
			m = i
		}
	}
	result = slice[m]
	return
}

// MinBy returns an element of StringSliceSlice containing the minimum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MinBy
func (slice StringSliceSlice) MinBy(less func(StringSlice, StringSlice) bool) (result StringSlice, err error) {
	l := len(slice)
	if l == 0 {
		err = errors.New("cannot determine the Min of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(slice[i], slice[m]) {
			m = i
		}
	}
	result = slice[m]
	return
}

func (slice StringSliceSlice) SkipTake(skip, take int) StringSliceSlice {
	var out StringSliceSlice
	skipped := 0
	taken := 0
	for _, item := range slice {
		if skip > skipped {
			skipped++
			continue
		}
		out = append(out, item)
		taken++
		if take > 0 && taken >= take {
			break
		}
	}
	return out

}
func swapStringSliceSlice(slice StringSliceSlice, a, b int) {
	slice[a], slice[b] = slice[b], slice[a]
}

// Insertion sort
func insertionSortStringSliceSlice(slice StringSliceSlice, less func(StringSlice, StringSlice) bool, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && less(slice[j], slice[j-1]); j-- {
			swapStringSliceSlice(slice, j, j-1)
		}
	}
}

// siftDown implements the heap property on slice[lo, hi).
// first is an offset into the array where the root of the heap lies.
func siftDownStringSliceSlice(slice StringSliceSlice, less func(StringSlice, StringSlice) bool, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && less(slice[first+child], slice[first+child+1]) {
			child++
		}
		if !less(slice[first+root], slice[first+child]) {
			return
		}
		swapStringSliceSlice(slice, first+root, first+child)
		root = child
	}
}
func heapSortStringSliceSlice(slice StringSliceSlice, less func(StringSlice, StringSlice) bool, a, b int) {
	first := a
	lo := 0
	hi := b - a
	// Build heap with greatest element at top.
	for i := (hi - 1) / 2; i >= 0; i-- {
		siftDownStringSliceSlice(slice, less, i, hi, first)
	}
	// Pop elements, largest first, into end of slice.
	for i := hi - 1; i >= 0; i-- {
		swapStringSliceSlice(slice, first, first+i)
		siftDownStringSliceSlice(slice, less, lo, i, first)
	}
}

// Quicksort, following Bentley and McIlroy,
// Engineering a Sort StringSlicetion, SP&E November 1993.
// medianOfThree moves the median of the three values slice[a], slice[b], slice[c] into slice[a].
func medianOfThreeStringSliceSlice(slice StringSliceSlice, less func(StringSlice, StringSlice) bool, a, b, c int) {
	m0 := b
	m1 := a
	m2 := c
	// bubble sort on 3 elements
	if less(slice[m1], slice[m0]) {
		swapStringSliceSlice(slice, m1, m0)
	}
	if less(slice[m2], slice[m1]) {
		swapStringSliceSlice(slice, m2, m1)
	}
	if less(slice[m1], slice[m0]) {
		swapStringSliceSlice(slice, m1, m0)
	}
	// now slice[m0] <= slice[m1] <= slice[m2]
}
func swapRangeStringSliceSlice(slice StringSliceSlice, a, b, n int) {
	for i := 0; i < n; i++ {
		swapStringSliceSlice(slice, a+i, b+i)
	}
}
func doPivotStringSliceSlice(slice StringSliceSlice, less func(StringSlice, StringSlice) bool, lo, hi int) (midlo, midhi int) {
	m := lo + (hi-lo)/2 // Written like this to avoid integer overflow.
	if hi-lo > 40 {
		// Tukey's Ninther, median of three medians of three.
		s := (hi - lo) / 8
		medianOfThreeStringSliceSlice(slice, less, lo, lo+s, lo+2*s)
		medianOfThreeStringSliceSlice(slice, less, m, m-s, m+s)
		medianOfThreeStringSliceSlice(slice, less, hi-1, hi-1-s, hi-1-2*s)
	}
	medianOfThreeStringSliceSlice(slice, less, lo, m, hi-1)
	// Invariants are:
	//	slice[lo] = pivot (set up by ChoosePivot)
	//	slice[lo <= i < a] = pivot
	//	slice[a <= i < b] < pivot
	//	slice[b <= i < c] is unexamined
	//	slice[c <= i < d] > pivot
	//	slice[d <= i < hi] = pivot
	//
	// Once b meets c, can swap the "= pivot" sections
	// into the middle of the slice.
	pivot := lo
	a, b, c, d := lo+1, lo+1, hi, hi
	for {
		for b < c {
			if less(slice[b], slice[pivot]) { // slice[b] < pivot
				b++
			} else if !less(slice[pivot], slice[b]) { // slice[b] = pivot
				swapStringSliceSlice(slice, a, b)
				a++
				b++
			} else {
				break
			}
		}
		for b < c {
			if less(slice[pivot], slice[c-1]) { // slice[c-1] > pivot
				c--
			} else if !less(slice[c-1], slice[pivot]) { // slice[c-1] = pivot
				swapStringSliceSlice(slice, c-1, d-1)
				c--
				d--
			} else {
				break
			}
		}
		if b >= c {
			break
		}
		// slice[b] > pivot; slice[c-1] < pivot
		swapStringSliceSlice(slice, b, c-1)
		b++
		c--
	}
	min := func(a, b int) int {
		if a < b {
			return a
		}
		return b
	}
	n := min(b-a, a-lo)
	swapRangeStringSliceSlice(slice, lo, b-n, n)
	n = min(hi-d, d-c)
	swapRangeStringSliceSlice(slice, c, hi-n, n)
	return lo + b - a, hi - (d - c)
}

func (slice StringSliceSlice) Split(fn func(t StringSlice) bool) (StringSliceSlice, StringSliceSlice) {
	var a StringSliceSlice
	var b StringSliceSlice
	for _, t := range slice {
		if fn(t) {
			a = append(a, t)
		} else {
			b = append(b, t)
		}
	}
	return a, b
}

func quickSortStringSliceSlice(slice StringSliceSlice, less func(StringSlice, StringSlice) bool, a, b, maxDepth int) {
	for b-a > 7 {
		if maxDepth == 0 {
			heapSortStringSliceSlice(slice, less, a, b)
			return
		}
		maxDepth--
		mlo, mhi := doPivotStringSliceSlice(slice, less, a, b)
		// Avoiding recursion on the larger subproblem guarantees
		// a stack depth of at most lg(b-a).
		if mlo-a < b-mhi {
			quickSortStringSliceSlice(slice, less, a, mlo, maxDepth)
			a = mhi // i.e., quickSortStringSliceSlice(slice, mhi, b)
		} else {
			quickSortStringSliceSlice(slice, less, mhi, b, maxDepth)
			b = mlo // i.e., quickSortStringSliceSlice(slice, a, mlo)
		}
	}
	if b-a > 1 {
		insertionSortStringSliceSlice(slice, less, a, b)
	}
}
